### ISSUE TITLE
[Feature] Implement legal moves of pieces

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#1]
**User story**: As a player, I want the system to calculate legal moves for pieces

**Acceptance tests**:
- [x]  Test that legal moves are calculated for a given piece;
- [x] Test that empty square throws exception;
- [x] Test that pawns can move two squares in first move;
- [x] Test that pawns only attacks in diagonals;
- [x] Test that pieces can block pawn from moving forward;
- [x] Test that pawns cannot capture in forward moves;
- [x] Test that black pawn only moves down;
- [x] Test that white pawn only moves up;
- [x] Test that pawn cannot move in diagonals when square is empty;
- [x] Test that possible moves for a piece includes the enemy piece coordinate;
- [x] Test that possible moves for a piece does not includes ally pieces;
- [x] Test that rook moves any square up, down, right, left;
- [x] Test that bishop moves any square in diagonals;
- [x] Test that knight moves in L shape;
- [x] Test that queen moves any square in all directions;
- [x] Test king moves one square in all directions;
- [x] Test that piece position changes correctly;
- [x] Test that algebraic notation is converted to vector;
- [x] Test that fen is converted to chessboard;
- [x] Test that chessboard is converted to fen string;

**Tasks**:
- [x] Create chessboard;
- [x] Create pieces;
- [x] Create directions;
- [x] Create coordinates;
- [x] Convert chessboard to fen;
- [x] Change position of pieces in chessboard;
- [x] Convert algebraic notation to vectors;
- [x] Convert fen string to chessboard;
- [x] Implement flyweight design pattern for coordinates;
- [x] Calculate legal moves;

**Story points**: 8
**Estimated hours**: 90
