### ISSUE TITLE
[Feature] Handle checkmate

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#10]
**User story**: As a player, I want the system to detect checkmates

**Acceptance tests**:
- [x] Test that a check without solution ends the match and sets a winner;
- [x] Test that player in double check can only move the king;
- [x] Test that a check can be solved by covering the king with a piece;
- [x] Test that a pinned piece cannot cover the king;
- [x] Test that a check can be solved by capturing the piece giving the check;
- [x] Test that a check can be solved by moving the king;
- [x] Test that the game continues if the check has a solution;
- [x] Test that king can only capture a piece if it’s not protected by another one;
- [x] Test that check and checkmate sign are added to the pgn move;

**Tasks**:
- [x] Create checkmate handler
- [x] Detect whether opponent is in check after a move
- [x] End the match and declare the current player as winner when there is no solution for a check
- [x] Try to solve check by covering the king with an ally piece
- [x] Try to solve the check by capturing the enemy piece
- [x] Try to solve the check by moving the king
- [x] Ensure that only the king can be moved in double check
- [x] Ensure that ally piece cannot cover the king when pinned by an enemy piece
- [x] Add check sign to pgn move when player is in check;
- [x] Add checkmate sign to pgn move when player is in checkmate;

**Notes**(optional):

**Estimated Story points**: 5

**Estimated hours**: 30
