### ISSUE TITLE
[Feature] Enforce fifty-move rule

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#11]
**User story**: As a player, I want the system to enforce the fifty-move rule

**Acceptance tests**:
- [x] Test that half move is incremented after a pawn or non capture move;
- [x] Test that half move is reset if a capture or non pawn move was made;
- [x] Test that full move is incremented after black`s move;
- [x] Test that match ends with draw when the half move count hits 100;

**Tasks**:
- [x] Create move count handler
- [x] Reset the counter on a capture or non pawn move
- [x] Increment the counter when there is no capture or when a pawn was moved
- [x] Increment fullmove counter on black`s move
- [x] End match with draw when halfmove counter hits 100

**Notes**(optional):

**Estimated Story points**: 1

**Estimated hours**: 5
