### ISSUE TITLE
[Feature] Detect stalemate positions

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#12]
**User story**: As a player, I want the system to detect stalemate

**Acceptance tests**:
- [x] Test that match ends with draw when there is no move and player is not in check;

**Tasks**:
- [x] Create stalemate handler
- [x] Check whether current chessboard position is stalemate
- [x] End match with draw on stalemate

**Notes**(optional):

**Estimated Story points**: 1

**Estimated hours**: 5
