### ISSUE TITLE
[Feature] Detect dead positions

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#13]
**User story**: As a player, I want the system to detect dead positions

**Acceptance tests**:
- [x] Test that match ends with draw if there is only king in the chessboard;
- [x] Test that match ends with draw if there is only king and king + bishop;
- [x] Test that match ends with draw if there is only king and king + knight;
- [x] Test that match ends with draw if there is only king and bishops of same color;

**Tasks**:
- [x] Create dead position handler
- [x] Check whether current chessboard position is a dead position
- [x] End match with draw on dead position

**Notes**(optional):

**Estimated Story points**: 1

**Estimated hours**: 7
