### ISSUE TITLE
[Feature] Handle timeout

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#14]
**User story**: As a player, I want the system to detect when the time runs out

**Acceptance tests**:
- [x] Test that each player has a countdown timer;
- [x] Test that timer only runs when it’s the turn of the player;
- [x] Test that timer of current player is stopped and the timer of opponent starts when the turns are switched;
- [x] Test that player has not timed out before playing a move;
- [x] Test that the player loses if his time runs out;

**Tasks**:
- [x] Create countdown
- [x] Set timeout limit
- [x] End match and declare winner on player timeout
- [x] Start and stop the timers when switching turns

**Notes**(optional):

**Estimated Story points**: 2

**Estimated hours**: 16
