### ISSUE TITLE
[Feature] Store matches in database

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#16]
**User story**: As a player, I want to store the match in database

**Acceptance tests**:
- [ ] Test that state of the match is stored in database after a legal move
- [ ] Test that an ongoing match is restored from database before a new move 
- [ ] Test that the system can send a command to create new the match
- [ ] Test that duplicated moves are ignored
- [ ] Test that invalid moves are not stored
- [ ] Test that match older than 1 day is deleted from database

**Tasks**:
- [x] Add database connection
- [x] Add database mapping for entities
- [x] Add command to create a match
- [x] Handle duplicated moves
- [x] Add command to play moves
- [x] Store new moves in database

**Notes**(optional): use redis as database

**Estimated Story points**: 5

**Estimated hours**: 52
