### ISSUE TITLE
[Feature] detect checks

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#3]
**User story**: As a player, I want the system to detect checks

**Acceptance tests**:
- [x] Piece hitting king of opposite color should return true
- [x] Piece not hitting the king of opposite color should return false

**Tasks**:
- [x] Add algorithm to detect checks

**Notes**(optional):

**Estimated Story points**: 1

**Estimated hours**: 4
