### ISSUE TITLE
[Feature] Handle en passant moves

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#4]
**User story**: As a player, I want to capture a pawn by en passant

**Acceptance tests**:
- [x] Possible moves for pawn should include the vulnerable enemy pawn;
- [x] The capture by en passant should remove the enemy pawn and change the ally pawn position properly;
- [x] Moving a pawn two squares forward in the first move should make it vulnerable;
- [x] A vulnerable pawn not captured should change the state to not vulnerable;

**Tasks**:
- [x] Check if vulnerable pawn is in the attacking range of the ally pawn;
- [x] Capture enemy pawn by en passant;
- [x] Check if a move makes pawn vulnerable;
- [x] Remove vulnerability after a move;

**Notes**(optional):

**Estimated Story points**: 3

**Estimated hours**: 17
