### ISSUE TITLE
[User Story] Commit moves

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#5]
**User story**: As a player, I want to commit a move

**Acceptance tests**:
- [ ] Verify that current player is not in check after the move;
- [ ] Verify that chessboard is saved as FEN string in database;
- [ ] Verify FEN string is formatted correctly before saving to database;
- [ ] Verify match state is saved to database;
- [ ] Verify that invalid moves are not saved to database;
- [ ] Test with not current player trying to move a piece;
- [ ] Test with ilegal moves;
- [ ] Test with player not in the match trying to move a piece;
- [ ] Test moving a piece when match is not ready to start;
- [ ] Test moving a piece when the match is finished;
- [ ] Test chessboard is formatted properly after being retrieved from database;
- [ ] Test current player trying to move the enemy piece;
- [ ] Test player making same move twice or more;
- [ ] Verify that several moves sent by same player is ignored upfront;

**Tasks**:
- [ ] Validate the move;
- [ ] Create database;
- [ ] Update the match in database;
- [ ] Retrieve match from database;
- [ ] Detect and handle same move made several times by same player;

**Notes**(optional):

**Estimated Story points**: 5

**Estimated hours**: 44
