### ISSUE TITLE
[Feature] Validate moves

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#7]
**User story**: As a player, I want the system to validate a move

**Acceptance tests**:
- [x] Test that legal move updates chessboard and match correctly;
- [x] Test that turns are switched after a valid move;
- [x] Test that current player cannot move enemy pieces;
- [x] Test that player cannot make moves after match is finished;
- [x] Test that only current player can make a move;
- [x] Test that illegal moves are discarded;
- [x] Test that player not in the match cannot move a piece;
- [x] Test that player cannot move a piece when match is not ready to start;
- [x] Test that valid moves are added to move list as PGN;
- [x] Test that matches and players has unique IDs;
- [x] Test that player cannot join same match twice;
- [x] Test that player cannot join a match that is full;
- [x] Test that a match cannot have two players of same color;
- [x] Test that player can only join one match;
- [x] Test that players are assigned to a match;
- [x] Test that match cannot have more than 2 players;
- [x] Test that match cannot start before it has 2 players;

**Tasks**:
- [x] Create match
- [x] Create player
- [x] Handle default moves
- [x] Discard illegal moves
- [x] Update match state
- [x] Update chessboard state
- [x] Assign player to a match
- [x] Store moves as PGN
- [x] Switch turns

**Notes**(optional):

**Estimated Story points**: 5

**Estimated hours**: 62
