### ISSUE TITLE
[Feature] Detect and handle promoting moves

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#8]
**User story**: As a player, I want to promote a pawn

**Acceptance tests**:
- [x] Test that pawn can promote to any piece but king and pawn;
- [x] Test that promoting move is added to PGN moves;
- [x] Test that pawn is converted to promoting piece;
- [x] Test that promoting move is handled correctly;

**Tasks**:
- [x] Detect promoting move
- [x] Handle promoting move
- [x] Convert pawn to piece being promoted
- [x] Add promoting move to PGN moves

**Notes**(optional):

**Estimated Story points**: 1

**Estimated hours**: 6
