### ISSUE TITLE
[Feature] Detect and handle castling moves

### ISSUE THREAD

**Issue by YagoBiermann** [YagoBiermann/OpenChess#9]
**User story**: As a player, I want to make a castling move

**Acceptance tests**:
- [x] Test that castling is handled correctly for both players;
- [x] Test that king in check cannot castle;
- [x] Test that king cannot castle if passing through a check when castling;
- [x] Test that castling availability is updated after castle move;
- [x] Test that castling availability is removed if king is moved;
- [x] Test that castling availability is removed if rook is moved;
- [x] Test that moving the king two squares to left or right is considered as castling;
- [x] Test that castling move is added to PGN moves;

**Tasks**:
- [x] Detect castling moves
- [x] Handle castling moves
- [x] Add castling move to PGN moves
- [x] Update castling availability

**Notes**(optional):

**Estimated Story points**: 1

**Estimated hours**: 8
